### ISSUE TITLE
Installed as informed by direction, but Slack will not "load"

### ISSUE THREAD

**Issue by P05TPWND** [caiceA/slack-black-theme#1]
After installing required fonts and using the provided sub-interop.js, Slack app will start, but endlessly "spins". I suspect it could be due to font, but am not sure. Is there some information that I could provide that would help debug? (Mac OSX 10.13.6)

**Comment by caiceA** [comment]
@P05TMAN are you using the latest file i pushed few hours ago?

**Comment by P05TPWND** [comment]
@caiceA I wasn't sure so I downloaded the latest file. Still experiencing the same issue:

![slack-issue](https://user-images.githubusercontent.com/4194045/44879517-1b093f80-ac67-11e8-97a1-87637e91079d.jpg)

The app does not progress past what's shown in the above picture.

**Comment by caiceA** [comment]
@P05TMAN  i tried again its working fine on my side 
please see here 

https://www.youtube.com/watch?v=WFipWZSlblM


1: you can remove your slack completely then download fresh and install 
2: if still cause this problem i won't recommend you to use this theme 

Thanks
KC

**Comment by P05TPWND** [comment]
@caiceA,

Thank you sir!

**Comment by caiceA** [comment]
@P05TMAN your problem solved?

**Comment by P05TPWND** [comment]
@caiceA 

No, unfortunately the problem is still there after fresh install; Slack was completely removed (i.e., from Applications, Library, etc). Still has the same issue.

**Comment by caiceA** [comment]
@P05TMAN  its strange I will look over the weekend I have same mac os version you mind if you share TeamViewer I can try with you. but if you don't need its ok.

**Comment by P05TPWND** [comment]
That's very kind of you to offer, however I cannot. The computer is a
company one. I will see if I get the same problem on my personal Mac and
update.

**Comment by caiceA** [comment]
@P05TMAN  ok i tested other mac its working fine. 
but yes great weekend!

**Comment by P05TPWND** [comment]
@caiceA,

Yep, this worked on my personal Mac, so definitely something on the company Mac I originally tried this on
:(

Oh well. Thanks again for jumping in to assist!

**Comment by caiceA** [comment]
@P05TMAN  its strange about your office Mac, maybe you can try on new OS Mujave after one month or so, I will help hopefully !!

**Comment by caiceA** [comment]
@P05TMAN  try downloading the new file from the server or repo and install on your office mac. Today Morning I had the same issue as your I fixed it for me i **HOPE** it will work on your office computer now.

**Comment by P05TPWND** [comment]
@caiceA,

The latest one worked beautifully on my work computer! Thank you!!
