### ISSUE TITLE
Issue with "All Threads" tab

### ISSUE THREAD

**Issue by linusphan** [caiceA/slack-black-theme#32]
The threads on this tab have white background with light grey text which makes it hard to read. I've reinstalled slack and re-replaced the file in order to see if it was the problem on my end but the style seems to be the same. Was this intentional? If not, a fix would be helpful :) Thanks!

**Comment by caiceA** [comment]
@linusphan you can use code from repo not from server in your case

**Comment by linusphan** [comment]
@caiceA I am not entirely sure what you mean. But here's some more information: I used the file stored in the `master branch` of the repo. I've also tried using the file from the download link in the `README.md` file. Neither seem to work. Thanks for your reply though :)

**Comment by caiceA** [comment]
Post Img of issue

**Comment by vietch2612** [comment]
<img width="695" alt="Screen Shot 2019-03-20 at 2 14 04 PM" src="https://user-images.githubusercontent.com/14076603/54665765-7d9a2e00-4b1a-11e9-9e27-813bfd1fd5ba.png">

@caiceA

**Comment by caiceA** [comment]
fixed

**Comment by seltzdesign** [comment]
Just wanted to report the same. I think I installed about 5 hours ago, now says "fixed 4 hours ago" :D

**Comment by vietch2612** [comment]
Dear @caiceA,

This issue still appears when I sent a new message to the thread.
<img width="698" alt="Screen Shot 2019-03-21 at 10 17 07 AM" src="https://user-images.githubusercontent.com/14076603/54731784-cad1da80-4bc2-11e9-830a-b203a887c2ef.png">

**Comment by caiceA** [comment]
@vietch2612 I don't know who idiot ( in my opinion ) worked on theme side in Slack ( official ) 

anyways I fixed this get the file from the server
