### ISSUE TITLE
Channel name black/illegible in fullscreen

### ISSUE THREAD

**Issue by JonStone904** [caiceA/slack-black-theme#64]
<img width="167" alt="image" src="https://user-images.githubusercontent.com/46907262/61368364-b1ccf380-a85b-11e9-8071-021a1d5e4ea2.png">

**Comment by caiceA** [comment]
That’s the old issue I fixed I can not find on my side maybe you restart your slack or re install the theme

**Comment by JonStone904** [comment]
Reinstalled the theme via shell/terminal and still showing black channel name. Also restarted and same thing. Currently uninstalling/reinstalling slack then theme

**Comment by natpuncher** [comment]
![Screen Shot 2019-07-17 at 13 23 50](https://user-images.githubusercontent.com/4374121/61368916-97187000-a897-11e9-884a-f7f2f14097e3.png)
same

**Comment by JonStone904** [comment]
still happening after uninstalling/reinstalling app and theme. only happening in full screen though

**Comment by caiceA** [comment]
try restarting app now

**Comment by JonStone904** [comment]
Looks excellent! Kudos for the quick response
